/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "AppResources" in a separate file.
*/
namespace ThisApp.Data
{
  /// <summary>
  /// Stub class to allow for custom code in the AppResources.cs file.
  /// </summary>
  public partial class AppResources : AppResourcesAutoGenerated { }

  /// <summary>
  /// Autogenerated base class for the AppResources.
  /// </summary>
  public abstract class AppResourcesAutoGenerated : Custom.Data.Item16
  {

    #region Dynamic Form
    public string ToolbarReuseInfo => String(fallback: "");
    public string LabelFromDataAvailable => String(fallback: "");
    public string ToolbarPermissionInfo => String(fallback: "");

    #endregion


    #region Dynamic Data Table

    public string LabelFirst => String(fallback: "");
    public string LabelLast => String(fallback: "");
    public string LabelTimestamp => String(fallback: "");

    #endregion

    #region Toolbar

    public string ToolbarViewData => String(fallback: "");
    public string ToolbarConfigure => String(fallback: "");
    public string ToolbarAppResources => String(fallback: "");

    #endregion

    #region Mailchimp and Footer Mailchimp

    public string MessageEnableMailchimp => String(fallback: "");
    public string MessageContainsMailchimp => String(fallback: "");
    public string MessageDefaultMailChimpKey => String(fallback: "");

    #endregion

    #region Footer Submit with Message

    public string MessageRecaptchaMissing => String(fallback: "");

    #endregion

    #region Footer Recaptcha

    public string MessageContainsRecaptcha => String(fallback: "");
    public string MessageRecaptchaWarning => String(fallback: "");

    #endregion

  }
}