/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "AppSettings" in a separate file.
*/
namespace ThisApp.Data
{
  public partial class AppSettings : AppSettingsAutoGenerated { }
  public abstract class AppSettingsAutoGenerated : Custom.Data.Item16
  {
    #region Dynamic Form
    public bool AdminHasPermission => Bool();
    #endregion

    #region Mailchimp
    public bool MailChimpShowWarning => Bool();
    public string MailchimpServer => String(fallback: "");

    public string MailchimpListId => String(fallback: "");
    public string MailchimpAPIKey => String(fallback: "");


    #endregion

    #region SendMail
    public string DefaultMailFrom => String(fallback: "");
    public string DefaultOwnerMail => String(fallback: "");

    #endregion


  }
}