/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "DynForm" in a separate file.
*/
namespace ThisApp.Data
{
  /// <summary>
  /// Empty class to allow for custom code in the DynForm.cs file.
  /// </summary>
  public partial class DynForm : DynFormAutoGenerated { }

  public abstract class DynFormAutoGenerated : Custom.Data.Item16
  {
    #region Dynamic Form

    public string DesignField => String(fallback: "");
    public bool ReuseConfig => Bool();
    public new string Title => String(fallback: "");
    public bool Recaptcha => Bool();

    #endregion

    #region Mailchimp

    public bool Mailchimp => Bool();

    #endregion

    #region Send Mail
    public string OwnerMailTemplate => String(fallback: "");
    public string OwnerMailCC => String(fallback: "");
    public string CustomerMailTemplate => String(fallback: "");
    public string CustomerMailCC => String(fallback: "");

    public bool CustomerSend => Bool();
    public bool OwnerSend => Bool();
    public string MailFrom => String(fallback: "");
    public string OwnerMail => String(fallback: "");

    #endregion

    #region EmailToCustomized

    public string OwnerMailSubject => String(fallback: "");

    #endregion

    #region EmailToCustomer
    public string CustomerMailSubject => String(fallback: "");

    #endregion

  }
}