/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "DynForm" in a separate file.
*/
namespace ThisApp.Data
{
  /// <summary>
  /// Empty class to allow for custom code in the DynForm.cs file.
  /// </summary>
  public partial class DynForm : DynFormAutoGenerated { }

  public abstract class DynFormAutoGenerated : Custom.Data.Item16
  {
    public new string Title => String(fallback: "");
    public bool ReuseConfig => Bool();

    #region GroupConfiguration

    public string DesignField => String(fallback: "");

    #endregion

    #region GroupRecaptcha
    public bool Recaptcha => Bool();
    public bool ShowRecaptchaIcon => Bool();

    #endregion

    #region GroupMailchimp
    public bool Mailchimp => Bool();
    #endregion


  }
}