/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "DynFormField" in a separate file.
*/
namespace ThisApp.Data
{
  public partial class FormResources : FormResourcesAutoGenerated { }

  public abstract class FormResourcesAutoGenerated : Custom.Data.Item16
  {
    public new string Title => String(fallback: "");
    public string Button => String(fallback: "");

    public string MessageSuccess => String(fallback: "");
    public string MessageError => String(fallback: "");
    public string MessageCustomerMailSend => String(fallback: "");

    public string MailBodyCustomer => String(fallback: "");
    public string MailBodyOwner => String(fallback: "");
    public string OwnerMailSubject => String(fallback: "");
    public string CustomerMailSubject => String(fallback: "");

  }
}