// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/hotbuild-autogen
// To extend it, create a "AppSettings.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppSettings
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.01.08
// App/Edition: Mobius Forms 6/staging
// User:        2sic Web-Developer
// When:        2024-02-16 18:53:14Z
namespace AppCode.Data
{
  // This is a generated class for AppSettings
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppSettings data. <br/>
  /// Generated 2024-02-16 18:53:14Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.AdminHasPermission`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class AppSettings: AppSettingsAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for AppSettings.
  /// </summary>
  public abstract class AppSettingsAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// AdminHasPermission as bool. <br/>
    /// To get nullable use .Get("AdminHasPermission") as bool?;
    /// </summary>
    public bool AdminHasPermission => Bool("AdminHasPermission");

    /// <summary>
    /// DefaultMailFrom as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DefaultMailFrom", scrubHtml: true) etc.
    /// </summary>
    public string DefaultMailFrom => String("DefaultMailFrom", fallback: "");

    /// <summary>
    /// DefaultOwnerMail as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DefaultOwnerMail", scrubHtml: true) etc.
    /// </summary>
    public string DefaultOwnerMail => String("DefaultOwnerMail", fallback: "");

    /// <summary>
    /// GdprEnabled as bool. <br/>
    /// To get nullable use .Get("GdprEnabled") as bool?;
    /// </summary>
    public bool GdprEnabled => Bool("GdprEnabled");

    /// <summary>
    /// MailchimpAPIKey as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailchimpAPIKey", scrubHtml: true) etc.
    /// </summary>
    public string MailchimpAPIKey => String("MailchimpAPIKey", fallback: "");

    /// <summary>
    /// MailchimpListId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailchimpListId", scrubHtml: true) etc.
    /// </summary>
    public string MailchimpListId => String("MailchimpListId", fallback: "");

    /// <summary>
    /// MailchimpServer as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailchimpServer", scrubHtml: true) etc.
    /// </summary>
    public string MailchimpServer => String("MailchimpServer", fallback: "");

    /// <summary>
    /// MailChimpShowWarning as bool. <br/>
    /// To get nullable use .Get("MailChimpShowWarning") as bool?;
    /// </summary>
    public bool MailChimpShowWarning => Bool("MailChimpShowWarning");

    /// <summary>
    /// TermsAndGdprCombined as bool. <br/>
    /// To get nullable use .Get("TermsAndGdprCombined") as bool?;
    /// </summary>
    public bool TermsAndGdprCombined => Bool("TermsAndGdprCombined");

    /// <summary>
    /// TermsEnabled as bool. <br/>
    /// To get nullable use .Get("TermsEnabled") as bool?;
    /// </summary>
    public bool TermsEnabled => Bool("TermsEnabled");
  }
}