// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FormResources.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FormResources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.00
// App/Edition: Mobius Forms 6/staging
// User:        2sic Web-Developer
// When:        2024-02-22 12:18:44Z
namespace AppCode.Data
{
  // This is a generated class for FormResources
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FormResources data. <br/>
  /// Generated 2024-02-22 12:18:44Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Button`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FormResources: FormResourcesAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for FormResources.
  /// </summary>
  public abstract class FormResourcesAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Button as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Button", scrubHtml: true) etc.
    /// </summary>
    public string Button => String("Button", fallback: "");

    /// <summary>
    /// ButtonNextStep as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ButtonNextStep", scrubHtml: true) etc.
    /// </summary>
    public string ButtonNextStep => String("ButtonNextStep", fallback: "");

    /// <summary>
    /// CustomerMailSubject as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("CustomerMailSubject", scrubHtml: true) etc.
    /// </summary>
    public string CustomerMailSubject => String("CustomerMailSubject", fallback: "");

    /// <summary>
    /// LabelGdpr as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelGdpr", scrubHtml: true) etc.
    /// </summary>
    public string LabelGdpr => String("LabelGdpr", fallback: "");

    /// <summary>
    /// LabelRequired as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelRequired", scrubHtml: true) etc.
    /// </summary>
    public string LabelRequired => String("LabelRequired", fallback: "");

    /// <summary>
    /// LabelSelect as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelSelect", scrubHtml: true) etc.
    /// </summary>
    public string LabelSelect => String("LabelSelect", fallback: "");

    /// <summary>
    /// LabelTerms as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelTerms", scrubHtml: true) etc.
    /// </summary>
    public string LabelTerms => String("LabelTerms", fallback: "");

    /// <summary>
    /// LabelTermsAll as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelTermsAll", scrubHtml: true) etc.
    /// </summary>
    public string LabelTermsAll => String("LabelTermsAll", fallback: "");

    /// <summary>
    /// LabelValidEmail as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelValidEmail", scrubHtml: true) etc.
    /// </summary>
    public string LabelValidEmail => String("LabelValidEmail", fallback: "");

    /// <summary>
    /// LabelValidFile as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelValidFile", scrubHtml: true) etc.
    /// </summary>
    public string LabelValidFile => String("LabelValidFile", fallback: "");

    /// <summary>
    /// MailBodyCustomer as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailBodyCustomer", scrubHtml: true) etc.
    /// </summary>
    public string MailBodyCustomer => String("MailBodyCustomer", fallback: "");

    /// <summary>
    /// MailBodyOwner as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailBodyOwner", scrubHtml: true) etc.
    /// </summary>
    public string MailBodyOwner => String("MailBodyOwner", fallback: "");

    /// <summary>
    /// MailCustomerContentWithData as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailCustomerContentWithData", scrubHtml: true) etc.
    /// </summary>
    public string MailCustomerContentWithData => String("MailCustomerContentWithData", fallback: "");

    /// <summary>
    /// MessageCustomerMailSend as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageCustomerMailSend", scrubHtml: true) etc.
    /// </summary>
    public string MessageCustomerMailSend => String("MessageCustomerMailSend", fallback: "");

    /// <summary>
    /// MessageDisabledFeature as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageDisabledFeature", scrubHtml: true) etc.
    /// </summary>
    public string MessageDisabledFeature => String("MessageDisabledFeature", fallback: "");

    /// <summary>
    /// MessageFormIncomplete as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageFormIncomplete", scrubHtml: true) etc.
    /// </summary>
    public string MessageFormIncomplete => String("MessageFormIncomplete", fallback: "");

    /// <summary>
    /// MessageMailFromError as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageMailFromError", scrubHtml: true) etc.
    /// </summary>
    public string MessageMailFromError => String("MessageMailFromError", fallback: "");

    /// <summary>
    /// MessageMailOwnerError as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageMailOwnerError", scrubHtml: true) etc.
    /// </summary>
    public string MessageMailOwnerError => String("MessageMailOwnerError", fallback: "");

    /// <summary>
    /// MessageNewsletterSuccess as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageNewsletterSuccess", scrubHtml: true) etc.
    /// </summary>
    public string MessageNewsletterSuccess => String("MessageNewsletterSuccess", fallback: "");

    /// <summary>
    /// MessageNewsletterUnexpectedError as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageNewsletterUnexpectedError", scrubHtml: true) etc.
    /// </summary>
    public string MessageNewsletterUnexpectedError => String("MessageNewsletterUnexpectedError", fallback: "");

    /// <summary>
    /// MessageSendError as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageSendError", scrubHtml: true) etc.
    /// </summary>
    public string MessageSendError => String("MessageSendError", fallback: "");

    /// <summary>
    /// MessageSending as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageSending", scrubHtml: true) etc.
    /// </summary>
    public string MessageSending => String("MessageSending", fallback: "");

    /// <summary>
    /// MessageSendOk as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageSendOk", scrubHtml: true) etc.
    /// </summary>
    public string MessageSendOk => String("MessageSendOk", fallback: "");

    /// <summary>
    /// OwnerMailSubject as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OwnerMailSubject", scrubHtml: true) etc.
    /// </summary>
    public string OwnerMailSubject => String("OwnerMailSubject", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => String("Title", fallback: "");
  }
}