/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "FormConfig" in a separate file.
*/
namespace AppCode.Data
{
  /// <summary>
  /// Empty class to allow for custom code in the FormConfig.cs file.
  /// </summary>
  public partial class SendMailConfig : SendMailConfigAutoGenerated { }

  public abstract class SendMailConfigAutoGenerated : Custom.Data.Item16
  {
    public bool OwnerSend => Bool();
    public bool CustomerSend => Bool();
    public string OwnerMail => String(fallback: "");
    public string OwnerMailCC => String(fallback: "");
    public string OwnerMailTemplate => String(fallback: "");
    public string CustomerMailCC => String(fallback: "");
    public string CustomerMailTemplate => String(fallback: "");
    public string MailFrom => String(fallback: "");

  }
}