// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/hotbuild-autogen
// To extend it, create a "FormData.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FormData
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.01.08
// App/Edition: Mobius Forms 6/staging
// User:        2sic Web-Developer
// When:        2024-02-19 15:56:29Z
using System;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for FormData
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FormData data. <br/>
  /// Generated 2024-02-19 15:56:29Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Files`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FormData: FormDataAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for FormData.
  /// </summary>
  public abstract class FormDataAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Files as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Files")
    /// </summary>
    public string Files => Url("Files");

    /// <summary>
    /// Get the file object for Files - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile FilesFile => File("FilesFile");

    /// <summary>
    /// Get the folder object for Files.
    /// </summary>
    public IFolder FilesFolder => Folder("FilesFolder");

    /// <summary>
    /// FormId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FormId", scrubHtml: true) etc.
    /// </summary>
    public string FormId => String("FormId", fallback: "");

    /// <summary>
    /// ModuleId as int. <br/>
    /// To get other types use methods such as .Decimal("ModuleId")
    /// </summary>
    public int ModuleId => Int("ModuleId");

    /// <summary>
    /// RawData as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("RawData", scrubHtml: true) etc.
    /// </summary>
    public string RawData => String("RawData", fallback: "");

    /// <summary>
    /// SenderIP as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SenderIP", scrubHtml: true) etc.
    /// </summary>
    public string SenderIP => String("SenderIP", fallback: "");

    /// <summary>
    /// Timestamp as DateTime.
    /// </summary>
    public DateTime Timestamp => DateTime("Timestamp");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => String("Title", fallback: "");
  }
}