/*
  * This file is automatically generated at 2024-01-31 17:59:00
  * DO NOT MODIFY IT BY HAND
  * If you need to extend it, create a partial class for "FormFieldConfig" in a separate file.
*/
namespace ThisApp.Data
{
  public partial class FormResources : FormResourcesAutoGenerated { }

  public abstract class FormResourcesAutoGenerated : Custom.Data.Item16
  {

    public new string Title => String(fallback: "");

    #region GroupValidation
    public string LabelRequired => String(fallback: "");
    public string LabelSelect => String(fallback: "");
    public string LabelValidEmail => String(fallback: ""); // Remove ?
    public string LabelValidFile => String(fallback: ""); // Remove ?
    #endregion

    #region GroupMessages
    public string MessageFormIncomplete => String(fallback: "");
    public string MessageSending => String(fallback: "");
    public string MessageSendOk => String(fallback: "");
    public string MessageCustomerMailSend => String(fallback: "");
    public string MessageSendError => String(fallback: "");
    public string MessageNewsletterSuccess => String(fallback: "");
    public string MessageNewsletterUnexpectedError => String(fallback: "");
    public string MessageMailFromError => String(fallback: "");
    public string MessageMailOwnerError => String(fallback: "");

    #endregion

    #region GroupButtons
    public string Button => String(fallback: "");
    public string ButtonNextStep => String(fallback: "");
    #endregion

    #region GroupMail
    public string MailCustomerContentWithData => String(fallback: "");

    #endregion

    #region FileUpload
    public string MessageDisabledFeature => String(fallback: "");
    #endregion

    #region MailSettings
    public string OwnerMailSubject => String(fallback: "");
    public string CustomerMailSubject => String(fallback: "");
    public string MailBodyCustomer => String(fallback: "");
    public string MailBodyOwner => String(fallback: "");

    #endregion

    #region GroupTerms

    public string LabelTermsAll => String(fallback: "");
    public string LabelTerms => String(fallback: "");
    public string LabelGdpr => String(fallback: "");

    #endregion

  }
}